### ISSUE TITLE
[backoffice] Rever artigo

### ISSUE THREAD

**Issue by secknv** [ABC-COVID19/API-backoffice#12]
[View no Adobe Xd](https://xd.adobe.com/view/209b97f4-223c-4887-7e4d-322de7aef2c2-56aa/screen/57b3e220-6b5c-4451-8ae8-50389bf1c9df/B-Rever-Artigo)

Esta view vai ser usada para editar a revisão associada ao artigo ou criar uma revisão caso não exista.

**As revisões só podem existir associadas a um artigo. E só pode existir uma para cada artigo.**

Na seguinte imagem já se incluem algumas alterações ao design no Adobe Xd:
![image](https://user-images.githubusercontent.com/16641477/79984696-740f9200-84a1-11ea-9a9d-5b9934587c06.png)

Os campos que estão na secção "Dados da Revisão", são editáveis pelo user.
## Notas e alterações sobre o design

1. Tal como mencionado no #9 , a barra de topo só precisa de um botão de logout para já.
2. Não é necessário ter as opções de formatação de texto.
3. Este link deve ser clickável
![image](https://user-images.githubusercontent.com/16641477/79985040-e7b19f00-84a1-11ea-8007-405024da3f9c.png)
4. As categorias deve dar para selecionar múltiplas e é preciso recolher o ID delas para depois passar nos requests.
![image](https://user-images.githubusercontent.com/16641477/79989734-1a5e9600-84a8-11ea-90ca-014386b18e49.png)
Talvez desse para usar uma coisa deste género: [Angular Multiselect Dropdown](https://www.npmjs.com/package/ng-multiselect-dropdown)
GET para `/api/category-trees`
5. O Tipo de Artigo é um dropdown single select. GET para `/api/article-types`. Também é preciso recolher o ID.
![image](https://user-images.githubusercontent.com/16641477/80000289-dcb43a00-84b4-11ea-9944-beee3163ef8a.png)

## Implementação
![image](https://user-images.githubusercontent.com/16641477/79985199-29dae080-84a2-11ea-842e-7d8499ace6c9.png)

Quando o user clicka neste botão:
1. Descobrir se existe revisão associada a este artigo:
   - Como uma revisão tem sempre um e um só artigo, no backend usámos um mapeamento de IDs. Isto significa que para saber se o artigo com o id XY tem revisão basta fazer o seguinte GET: `/api/revisions?id.equals=XY`.
      - Se existir, a response será a revisão.
      - Se não existir, a response será `[]`.
2. Caso não Revisão:
   1. No ato de salvar fazer um POST para `/api/revisions` com:
      (comentários/explicação a com "#")
      ```json
      {
        "article": {"id": 0}, #_passar_o_ID_do_artigo_que_está_a_ser_revisto
        "atype": {"id": 0},  #_passar_o_ID_do_tipo_de_artigo
        "ctrees": [
          {"id": 0}, {"id": 1} #_passar_os_ID_das_várias_categorias
        ],
        "author": "string",
        "country": "string",
        "isPeerReviewed": true,
        "keywords": "string",
        "reviewDate": "yyyy-mm-dd", #_data_formatada_do_momento_de_criação_da_revisão
        "reviewNotes": "string",
        "reviewState": "Hold",
        "reviewer": "string",
        "summary": "string",
        "title": "string"
      }
      ```
3. Caso haja Revisão:
   1. Mostrar a view com os dados da revisão dentro dos campos para se poderem editar
   2. No ato de salvar, fazer um PUT para `/api/revisions` com:
      (aplicam-se os comentários no json acima também)
      ```json
      {
        "id": 0, #_passar_o_ID_da_revisão_que_estamos_a_alterar
        "atype": {"id": 0},
        "ctrees": [
          {"id": 0}, {"id": 1}
        ],
        "author": "string",
        "country": "string",
        "isPeerReviewed": true,
        "keywords": "string",
        "reviewDate": "2020-04-22",
        "reviewNotes": "string",
        "reviewState": "Hold",
        "reviewer": "string",
        "summary": "string",
        "title": "string"
      }
      ```

**Comment by VitorDiass** [comment]
@secknv 
Na primeira imagem, o dropdown "País" terá que conteúdo? Lista de países?

**Comment by secknv** [comment]
@VitorDiass 
Não é um dropdown, é um campo de texto pequeno - sorry

**Comment by VitorDiass** [comment]
Aqui deixo uma lista de coisas que ficaram por resolver tanto na página em específico como no geral.

**Página:** 
O campo "Link" não está clicável
O dropdown da categoria e do tipo de artigo não estão a apresentar quando já existe revisão (não sei até que ponto pode ou não ser bug por parte da component [Angular Multiselect Dropdown](https://www.npmjs.com/package/ng-multiselect-dropdown).
Testar o método salvar(como ou sem revisão já existente) para verificar se está a gravar como pretendido.

**Geral:**
Apresentação de mensagem de erro no caso de haver problemas com algum pedido.
Responsividade em geral

**Comment by secknv** [comment]
### Caso revisão já existente:
1. O botão salvar não faz nada (parece não ter acção associada, simplesmente não acontece nada na pag nem são feitos nenhuns requests)

### Caso não exista revisão:
1. O botão salvar está a fazer um post para os articles
![post](https://user-images.githubusercontent.com/16641477/81019661-04b17f00-8e5f-11ea-8e9d-fbd56300870b.gif)

2. Os seguintes campos devem ficar required (porque são obrigatorios para o API):
   - Tópico do Artigo
   - Sinopse
   - Revisor
   - Autor
3. Meter tick na "Em Curso" como default para os artigos que não tem revisão
![image](https://user-images.githubusercontent.com/16641477/81019828-5fe37180-8e5f-11ea-971a-1fbb90d815af.png)

4. Obrigar a selecionar 1 (e só um) Tipo de Artigo
5. Obrigar a selecionar pelo menos uma categoria.
6. As revisões pertencem às subcategorias, deve dar para selecionar as subcategorias no dropdown.
    - Não há revisões nas categorias top-level a não ser no caso especial "destaques". A categoria "highlights" neste momento não está a ser usada.
    - Sugestão de como gerar os items do dropdown: https://jsfiddle.net/ha4g1d9y/

**Comment by VitorDiass** [comment]
[Problemas referidos]
1- Corrigido no caso de não haver revisão
1- Necessários testes para verificar se está tudo ok.
2- Adicionada verificação para os campos serem required.
3-Estado "Em curso" passa a default no caso de não ter revisão
4 e 5 - ok
6. Segui a sugestao do @secknv mas por algum motivo o dropdown não está a apresentar a informação. Tentem com outras componentes mas sem sucesso.

Feita ligação do botão "Rever" na listagem dos artigos para a página de refever.

**Comment by secknv** [comment]
### Problemas por resolver:
1. No data no dropdown das categorias
2. Quando se está a editar uma revisão já existente:
    - As categorias e o ArticleType não aparecem pre selecionados.
    - Botão salvar parecer não fazer nada.

3. Quando se cria nova revisão:
    - Botão salvar ativa uma alert window que avisa sobre os campos obrigatorios, é preciso arranjar o texto: 
![image](https://user-images.githubusercontent.com/16641477/81192947-b90fea00-8fb2-11ea-9674-567190738da7.png)
