### ISSUE TITLE
fix responsividade rever-artigo

### ISSUE THREAD

**Issue by secknv** [ABC-COVID19/API-backoffice#37]
### Arranjar problemas com a responsividade - smaller screens:
![image](https://user-images.githubusercontent.com/16641477/82350075-cc7b7600-99f2-11ea-89b1-c3ca384d4956.png)

![image](https://user-images.githubusercontent.com/16641477/82350210-f6349d00-99f2-11ea-8de3-86a210ba9e4d.png)

**Comment by guilhermecostalopes** [comment]
Este está corrigido desta forma ?
![image](https://user-images.githubusercontent.com/24395029/82398352-10896d80-9a29-11ea-9301-a14b24989916.png)

**Comment by secknv** [comment]
e como fica esta parte quando se reduz o ecrã?
![image](https://user-images.githubusercontent.com/16641477/82420600-d72c1e80-9a77-11ea-9a3b-b36f0bb07ed2.png)

**Comment by guilhermecostalopes** [comment]
Vou ver

**Comment by guilhermecostalopes** [comment]
> e como fica esta parte quando se reduz o ecrã?
> ![image](https://user-images.githubusercontent.com/16641477/82420600-d72c1e80-9a77-11ea-9a3b-b36f0bb07ed2.png)

Este não tinha analisando vou ver agora

**Comment by guilhermecostalopes** [comment]
Ajustado
