### ISSUE TITLE
página de alteração da password

### ISSUE THREAD

**Issue by secknv** [ABC-COVID19/API-backoffice#38]
criar link na navbar para a pág de editar password
atualmente acessível através da route `/legacy/account/password`

**Comment by guilhermecostalopes** [comment]
Ao redirecionar para a rota **/legacy/account/password** ele dá erro **404**. Imagem em anexo. Creio que ainda não foi mapeado.

![image](https://user-images.githubusercontent.com/24395029/82397011-cfdc2500-9a25-11ea-9f8a-c6478afcfffc.png)

Coloquei este ícone, seguindo a mesma cor do logout. É para ficar neste lugar mesmo ?
![image](https://user-images.githubusercontent.com/24395029/82397224-51cc4e00-9a26-11ea-9360-5c69aeabf9ff.png)

Fico no aguardo

**Comment by secknv** [comment]
estás com o branch desatualizado

**Comment by guilhermecostalopes** [comment]
Agora sim.
