### ISSUE TITLE
melhorar botões navbar

### ISSUE THREAD

**Issue by secknv** [ABC-COVID19/API-backoffice#39]
tornar estes botões mais óbvios e intuitivos
![image](https://user-images.githubusercontent.com/16641477/82351096-07ca7480-99f4-11ea-96a2-caccd88d3496.png)

**Comment by guilhermecostalopes** [comment]
A principio coloquei os ícones.
![image](https://user-images.githubusercontent.com/24395029/82443477-f1fe9300-9a77-11ea-8254-8300b7aedaa0.png)

Mas estava pensando, não seria bom colocar algum contador ?
Algo tipo o badge, conforme imagem.
![image](https://user-images.githubusercontent.com/24395029/82444863-3854f180-9a7a-11ea-9e6f-1ced297711b7.png)

ou

![image](https://user-images.githubusercontent.com/24395029/82445157-b913ed80-9a7a-11ea-9c2d-5efb935176e8.png)

https://getbootstrap.com/docs/4.5/components/badge/. Mas para este nymero funcionar, deve ter um endpoint que faz a contagem e o angular, buscar este endpoint a todo momento.

São só ideías para melhoras.

Fico no aguardo

**Comment by secknv** [comment]
os endpoints da contagem são:
- revisões: `/services/icamapi/api/revisions/count`
- artigos: `/services/icamapi/api/articles/count`

Acho que a opção melhor é 
![image](https://user-images.githubusercontent.com/16641477/82448105-32263b80-9aa1-11ea-884a-71d23313097a.png)
Além disto mudava também a cor das letras para ficar branco como o "Logout"

**Comment by guilhermecostalopes** [comment]
Vou fazer as alterações

**Comment by guilhermecostalopes** [comment]
> * revisões: `/services/icamapi/api/revisions/count`
> * artigos: `/services/icamapi/api/articles/count`

Isto é no back end ou um serviço criado no frontend ?

**Comment by secknv** [comment]
É no backend

**Comment by guilhermecostalopes** [comment]
Imagem, conforme definição
![image](https://user-images.githubusercontent.com/24395029/82564501-3f99ff00-9b4f-11ea-8af9-9a9ac66a40bc.png)
